---
title: "Caracterización comunas RM"
subtitle: "Contexto Covid-19"
author: "Javiera Rojas Cifuentes"
date: '\today'
bibliography: "insumos/Referencias.bib"
csl: "insumos/apa-single-spaced.csl"
output:
  rmarkdown::html_vignette:
    css: /home/rstudio-user/R/x86_64-pc-linux-gnu-library/4.0/rmarkdown/rmarkdown/templates/html_vignette/resources/vignette.css
vignette: |
  %\VignetteIndexEntry{Caracterización comunas RM} %\VignetteEngine{knitr::rmarkdown} %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(comment=NA, prompt=FALSE, cache=FALSE, echo=TRUE, message = FALSE, warning = FALSE, results='asis')
# Esta segunda línea se agrega para indicar que la carpeta desde donde debe partir buscando archivos es la del proyecto R
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
library(summarytools)
library(magrittr)
st_options(bootstrap.css     = FALSE,
           plain.ascii       = FALSE,
           style             = "rmarkdown",
           dfSummary.silent  = TRUE,
           subtitle.emphasis = FALSE,
           lang = "es", 
           footnote = "Fuente: Elaboración propia en base a CASEN (2017)")
                                          
```

```{r, echo=FALSE}
st_css()
```

```{r cargar-datos, echo = FALSE}
# Con este comando se carga el archivo (lista) que contiene los resultados
CASENRM <- readRDS("datos/2-intermedios/casen-editada.rds")
resultados <- readRDS("datos/3-resultados/resultados-reporte.rds")

```

> **Tabla 1**. Frecuencias conjuntas: Nivel Educacional según Comuna

```{r, echo=F}
tabla1<- ctable(CASENRM$Comuna, CASENRM$Educación, prop = "r",
       weights = CASENRM$expc, style = 'rmarkdown', useNA = "no", 
       totals = F)
print(tabla1, method = "render", headings = F)
```

```{r, echo=F}
print(resultados[[1]], method = "render", headings = F)
```
